name = "MagneticReadHead"
uuid = "3f5657c2-1c21-11e9-2267-d379952df7a3"
authors = ["Lyndon White <lyndon.white@invenialabs.co.uk>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
